### ISSUE TITLE
Request: Toggle Check Box to Only Show Token Art

### ISSUE THREAD

**Issue by Methose** [Eriku33/Foundry-VTT-Image-Hover#10]
Hello,

I would love to use image hover so my player can easily see the art for the monsters I use (horror campaign) but some of my monsters (like the werewolves) shape-shift by using the Wildcard tokens. If I used image hover on one of them, it would only display their character art, not their token art when they shape-shift. Also, it would stop any spoilers from the players mousing over a wolf and seeing their human form character art, for example. Could the module have a check box to only show token art when hovered over?

Thanks.

**Comment by Eriku33** [comment]
Hello Methose,

Currently I'm still trying to figure out the logistics of a check box and where I would even put it.
For now, if you update:
I've added a setting "Art on hover" in the module settings.
You can change it such that all wildcard tokens will show the token art instead of the character art.

**Comment by Methose** [comment]
I absolutely love the new change! The drop down menu for being able to select token art (and wildcard tokens) is exactly what I wanted! Thanks again!
