### ISSUE TITLE
Images showing for some but mostly not

### ISSUE THREAD

**Issue by nullpunktTUD** [Eriku33/Foundry-VTT-Image-Hover#2]
I love the idea of this module but I am having a bit of trouble getting it to work. It is showing the avatar image for some of my players' characters, but not all of them, and not showing anythign for all of my NPCs.

I tried to figure out what the difference is between the ones that work and the ones that don't, but I can't seem to find anything systematic.

Have you encountered this before? Any idea how to fix it?

**Comment by Eriku33** [comment]
Hello, there was a issue with Wildcard tokens not showing up but that was fixed in v1.0.5, I would recommend updating to the latest version and checking if that fixes the issue.
There is also a setting named Required actor permission which is default set to None (Anyone can hover over anything) which is probably what you want.

Most likely updating will fix the issue, otherwise I might of forgot to support one of the file extensions (.png, .webm , .svg, .webp etc...) or a game system I haven't tested it on. Let me know if that's the case.
Feel free to message me on Discord (Eriku#2108) if you want me to join a session and check it out.

**Comment by nullpunktTUD** [comment]
I am using the current version. The images are png and the system is pf1e, so nothing too exotic, I would think. I sent you a friend request on Discord, it would be super awesome if you would check it out!

**Comment by Eriku33** [comment]
Incompatibility with Tokenizer module, Tokenizer seems to add extra numbers to end of files.

**Comment by Eriku33** [comment]
Fixed in version v1.0.7

Note that Tokenizer module creates new image files so if you don't change the default character/actor art when using tokenizer, it may show the default image when hovered.
