### ISSUE TITLE
Image shows up under Small Time

### ISSUE THREAD

**Issue by JamzTheMan** [Eriku33/Foundry-VTT-Image-Hover#26]
Would it be possible to up the z-index for the image? Right now, if you have Small Time module open, it is on top of the image. I think it has a z-index of around 70 IIRC.

**Comment by Vesselchuck** [comment]
**SmallTime** has a `z-index: 100` and his module cannot surpass that `z-index` no matter what. That's all because it is a child to `div.hud` which sets the maximum `z-index: 70`. So before anything, it would be better to make this module's parent `body.vtt game system-pf2e`, similarly to **SmallTime**.

**Comment by Vesselchuck** [comment]
So if someone wants a quick fix here some CSS for you:
```
#smalltime-app {
	z-index: 69 !important;
}
```

**Comment by Eriku33** [comment]
The module owner of Smalltime has kindly lowered the z-index of their UI. If you update their module (smalltime), this should fix the issue.
