### ISSUE TITLE
Getting errors in console

### ISSUE THREAD

**Issue by Vesselchuck** [Eriku33/Foundry-VTT-Image-Hover#44]
![image](https://user-images.githubusercontent.com/70449411/208868546-a18d377e-ac40-4205-b447-5226d64dad82.png)
![image](https://user-images.githubusercontent.com/70449411/208868602-2325343b-ee5b-4b8c-b3e1-247674bf377d.png)

**Comment by Eriku33** [comment]
![image](https://user-images.githubusercontent.com/47860010/208869504-f39eed51-49c9-4123-9a82-cc9425ec9734.png)
Hello, fix is to change line 452 from `if (!showSpecificArt) {` to `if (!showSpecificArt && canvas.hud.imageHover){` in the `image-hover.js` file.
If you need a urgent fix, otherwise I will released a version soon.

**Comment by Vesselchuck** [comment]
Thank you very much, but I'll wait for the new version!

**Comment by Eriku33** [comment]
This issue has been resolved, let me know if it still occurs :)
