### ISSUE TITLE
Console error on loading Foundry

### ISSUE THREAD

**Issue by weepingminotaur** [Eriku33/Foundry-VTT-Image-Hover#46]
Getting this console error when I load into Foundry. Wasp, the Sequencer dev, said this:

"Looks like image-hover is registering and executing code touching the visual element of tokens in its preUpdateToken hook before the canvas has been initialized
IE, it is trying to clear something on the visual representation of the token on the canvas before it exists (before it has been rendered)"

<img width="551" alt="Screen Shot 2023-05-18 at 12 35 56 AM" src="https://github.com/Eriku33/Foundry-VTT-Image-Hover/assets/90105219/a81badb3-2109-4f2d-beaf-fdcfd0b3e6c7">

**Comment by Eriku33** [comment]
Hello :)
Which version of Foundry are you using?

Thanks

**Comment by weepingminotaur** [comment]
Foundry v10, build 291. Pathfinder 2e 4.11.2

**Comment by RexxDM** [comment]
![image](https://github.com/Eriku33/Foundry-VTT-Image-Hover/assets/134309842/bb1599e4-ee98-4d98-b592-0dde39cd1a88)

Figured I'd drop in and mention that I too am getting a similar / the same "foundry.js.747" error in the console when loading Foundry..

Foundry Version 10 - Build 291
System: DnD 5E Version 2.1.5
Image Hover Version: 3.0.0
(And just in case it matters since it's part of the error?)
Sequencer Version: 3.0.8

**Comment by Eriku33** [comment]
Hello, it should have been fixed by #47. 
Please update the module and let me know if the issue still persists.

💖
Eric

**Comment by weepingminotaur** [comment]
Updated and it looks like it's fixed -- not getting the console error. Thank you!

**Comment by Eriku33** [comment]
Thanks for bringing this to my attention, hopefully, this is fixed in the new release by #49 .
Let me know if any other errors occur.

Thanks!

**Comment by RexxDM** [comment]
I am no longer getting that error (At least not by the same testing I did before) - So it seems to be fixed
