### ISSUE TITLE
Foundry Build 11.308+ Image Hover Placement Bug

### ISSUE THREAD

**Issue by CobyKromis** [Eriku33/Foundry-VTT-Image-Hover#55]
Image hover art is forced to top left of scene regardless of settings. Image is also tied to scene grid rather than to client screen i.e., zooming out or panning can make the hover go out of the window even though you are still hovering the token. This bug has been confirmed with multiple users on multiple Foundry builds post 11.307.

**Comment by Eriku33** [comment]
Hello,

Currently can't seem to reproduce this issue. As you can see I only have 1 active module(image hover) and am on the latest Foundry version, I also quickly checked the versions from 11.307+.
![image](https://github.com/Eriku33/Foundry-VTT-Image-Hover/assets/47860010/2ea87adb-1582-4b8e-af3b-f8e21a466936)

If possible, could you double-check if it's a module compatibility issue? The quickest way would be to create a new world and only have the Image Hover module active. Other than this could you also provide the web browser (if any) and the dnd system you're using?

**Comment by sheitmar** [comment]
Just wanted to chime in - I'm also experiencing this issue. I did as you recommended by using the latest foundry, started a new world and selected only the Image Hover module.

I use Firefox and Chrome, and this behavior is consistent for both. In addition, and I'm not sure if this is intentional (I'm pretty new to Foundry), but when scrolling in and out of the map, it seems like the image is static to the map, as it will zoom in and out with the map, locked to a specific point on the map, being the top left of the map area. I would have expected it to not be affected by the zoom level. I'm using the DND5e - Fifth Edition System (2.3.1) edition.
![image_hover](https://github.com/Eriku33/Foundry-VTT-Image-Hover/assets/63080194/31b2a9f3-3ef7-421a-9fff-c22d84ebeaba)

**Comment by Eriku33** [comment]
Thanks for the edit, this is very helpful information ❤️.

**Comment by Eriku33** [comment]
Hello,

This has been fixed in the latest release which is currently only compatible with Foundry v12.
As always, let me know if anything else comes up, and thanks for the additional bug information.
Thanks!
